project:
  type: book

profile:
  group:
    - [html, pdf]

metadata-files:
  - _book-structure.yml

lang: es

website:
  title: "IASI Infra"

  sidebar:
    style: docked
    search: true
    contents: auto
